# Generated by Django 4.1.3 on 2022-12-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('documentation', models.TextField()),
                ('metadata', models.CharField(max_length=200)),
                ('suite_setup', models.CharField(max_length=200, verbose_name='suite setup')),
                ('suite_teardown', models.CharField(max_length=200, verbose_name='suite teardown')),
                ('force_tags', models.CharField(max_length=200, verbose_name='force tags')),
                ('test_setup', models.CharField(max_length=200, verbose_name='test setup')),
                ('test_teardown', models.CharField(max_length=200, verbose_name='test teardown')),
                ('test_timeout', models.CharField(max_length=200, verbose_name='test timeout')),
                ('library', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('documentation', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('setup', models.CharField(max_length=200)),
                ('teardown', models.CharField(max_length=200)),
                ('template', models.CharField(max_length=200)),
                ('timeout', models.CharField(max_length=200)),
                ('arguments', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsuite')),
            ],
        ),
    ]
