# Generated by Django 4.1.3 on 2022-12-06 16:10

import os
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        FileLocations = apps.get_model('tests', 'FileLocations')
        FileLocations.objects.create(name='robot_dir')

    operations = [
        migrations.RunPython(insertData),
    ]