# Generated by Django 4.1.3 on 2022-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='arguments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='setup',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='teardown',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='template',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='timeout',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='force_tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='force tags'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='library',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='metadata',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='suite_setup',
            field=models.CharField(blank=True, max_length=200, verbose_name='suite setup'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='suite_teardown',
            field=models.CharField(blank=True, max_length=200, verbose_name='suite teardown'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_setup',
            field=models.CharField(blank=True, max_length=200, verbose_name='test setup'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_teardown',
            field=models.CharField(blank=True, max_length=200, verbose_name='test teardown'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_timeout',
            field=models.CharField(blank=True, max_length=200, verbose_name='test timeout'),
        ),
    ]
