# Generated by Django 4.1.3 on 2022-12-15 17:10

import os
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        Setting = apps.get_model('tests', 'Setting')
        Setting.objects.create(name='robot_dir')
        Setting.objects.create(name='tests_dir')

    operations = [
        migrations.RunPython(insertData),
    ]