# Generated by Django 4.1.3 on 2022-12-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20221208_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'ordering': ('name',)},
        ),
    ]
