# Generated by Django 4.1.3 on 2022-12-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20221207_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='force_tags',
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testcase')),
                ('test_suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testsuite')),
            ],
        ),
    ]
