# Generated by Django 4.1.3 on 2022-12-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_testcase_arguments_alter_testcase_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='suite',
            new_name='test_suite',
        ),
    ]
