# Generated by Django 4.1.3 on 2022-12-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_testsuite_metadata_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='template',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='libraries',
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsuite')),
            ],
        ),
    ]
